sonar.projectKey=book4u-final
sonar.projectName=Book4u Analysis
sonar.projectVersion=1.0

sonar.host.url=https://sonar.vereshchak.online

sonar.sources=.
sonar.exclusions=node_modules/**, public/**, package-lock.json
sonar.sourceEncoding=UTF-8
